# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MQPlayer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MQPlayer
  use_frameworks!
  pod 'Masonry'
  pod 'YYModel', '~> 1.0.4'
  pod 'FMDB'
  pod 'LKDBHelper'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManager'
  pod 'JPush-iOS-SDK'
  pod 'JKCountDownButton'
  pod 'YYCache'
  pod 'MJRefresh'
  pod 'SDWebImage'
#  pod 'ZFPlayer', '~> 3.0'
#  pod 'ZFPlayer/ControlView', '~> 3.0'
#  pod 'ZFPlayer/AVPlayer', '~> 3.0'
  pod 'AFNetworking'
  pod 'NODataPlaceholderView', '~> 1.0.2'
  pod 'KRVideoPlayer'
end
