# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AK88' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MQPlayer
  use_frameworks!
  pod 'YYModel', '~> 1.0.4'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManager'
  pod 'SDWebImage'
  pod 'AFNetworking'
end
